services:
  - type: web
    name: zuvio-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt && alembic upgrade head"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: POSTGRES_SERVER
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: BACKEND_CORS_ORIGINS
        value: "https://zuvio-frontend.onrender.com,http://localhost:3000"
      - key: STORAGE_BUCKET_NAME
        sync: false
      - key: STORAGE_ACCESS_KEY
        sync: false
      - key: STORAGE_SECRET_KEY
        sync: false
      - key: STORAGE_REGION
        sync: false
      - key: STORAGE_ENDPOINT_URL
        sync: false
