"""Add sharing models

Revision ID: bb3784490e96
Revises: 5d7b62bef9a7
Create Date: 2026-08-29 11:55:07.105539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3784490e96'
down_revision: Union[str, Sequence[str], None] = '5d7b62bef9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(file_id IS NULL AND folder_id IS NOT NULL) OR (file_id IS NOT NULL AND folder_id IS NULL)', name='chk_public_link_resource_xor'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_links_created_by_id'), 'public_links', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_public_links_file_id'), 'public_links', ['file_id'], unique=False)
    op.create_index(op.f('ix_public_links_folder_id'), 'public_links', ['folder_id'], unique=False)
    op.create_index(op.f('ix_public_links_id'), 'public_links', ['id'], unique=False)
    op.create_index(op.f('ix_public_links_token'), 'public_links', ['token'], unique=True)
    op.create_table('shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(file_id IS NULL AND folder_id IS NOT NULL) OR (file_id IS NOT NULL AND folder_id IS NULL)', name='chk_share_resource_xor'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_id', 'file_id', name='uq_share_recipient_file'),
    sa.UniqueConstraint('recipient_id', 'folder_id', name='uq_share_recipient_folder')
    )
    op.create_index(op.f('ix_shares_created_by_id'), 'shares', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_shares_file_id'), 'shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_shares_folder_id'), 'shares', ['folder_id'], unique=False)
    op.create_index(op.f('ix_shares_id'), 'shares', ['id'], unique=False)
    op.create_index(op.f('ix_shares_recipient_id'), 'shares', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_recipient_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_folder_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_file_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_created_by_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_public_links_token'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_id'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_folder_id'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_file_id'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_created_by_id'), table_name='public_links')
    op.drop_table('public_links')
    # ### end Alembic commands ###
